apiVersion: v1
kind: Service
metadata:
  name: subtext-api
  namespace: subtext
spec:
  selector:
    app: subtext-api
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
  type: ClusterIP
