apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: subtext

resources:
- namespace.yaml
- api-deployment.yaml
- api-service.yaml
- network-policies.yaml

images:
- digest: sha256:8fe905b59acf48aa5b7ada9348ee60eec19cfab6266f3529c534246681864eee
  name: ghcr.io/madfam-org/subtext-api
  newName: ghcr.io/madfam-org/subtext-api
