apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: subtext

resources:
  - namespace.yaml
  - api-deployment.yaml
  - api-service.yaml
  - network-policies.yaml

images:
  - name: ghcr.io/madfam-org/subtext-api
    newName: ghcr.io/madfam-org/subtext-api
    newTag: latest
